@startuml(id=COMPLETO)
!include Celda.puml!SINSUBCLASES
!include Obstaculo.puml!SINSUBCLASES
!include Sorpresa.puml!SINSUBCLASES
!include CeldaBorde.puml
!include CeldaInterna.puml
!include CeldaEsquina.puml
!include EstadoCelda.puml
@enduml

@startuml(id=SINSUBCLASES)
!include EstadoCelda.puml!SINSUBCLASES
abstract class Celda{
    + Celda( EstadoCelda estado ): Celda
    + avanzarEn( Vehiculo v ): Evento
    + setCeldaOpuesta( Celda celda, Direccion direccion )
    + {abstract} getCelda( Direccion direccion ): Celda
    + {abstract} setCelda( Celda nueva, Direccion direccion)
}

Celda -down--> EstadoCelda
@enduml

