@startuml
!include DiagramaClase_Celda.puml!SINSUBCLASES
!include DiagramaClase_Obstaculo.puml!SINSUBCLASES
!include DiagramaClase_Sorpresa.puml!SINSUBCLASES

Obstaculo --|> EstadoCelda
Comun ..|> EstadoCelda
Sorpresa ..|> EstadoCelda

class Comun{
    + avanzarEn( Vehiculo v ): ModificadorMovimiento
}
@enduml

@startuml(id=SINSUBCLASES)
class Celda{
    + avanzarEn( Vehiculo v ): ModificadorMovimiento
}

Celda --> EstadoCelda
Celda -> "4" Celda

interface EstadoCelda{

    + {abstract} avanzarEn( Vehiculo v ): ModificadorMovimiento
}

@enduml

