@startuml
!include DiagramaClase_Vehiculo.puml!SINSUBCLASES

Moto .up.|> Vehiculo
Auto .up.|> Vehiculo
cuatroPorCuatro .up.|> Vehiculo

class Moto{
    + avanzarComun(): Movimiento
    + avanzarPiquete(): Movimiento
    + avanzarControlPolicial(): Movimiento
    + avanzarPozo(): Movimiento
}
class Auto{
    + avanzarComun(): Movimiento
    + avanzarPiquete(): Movimiento
    + avanzarControlPolicial(): Movimiento
    + avanzarPozo(): Movimiento
}
class cuatroPorCuatro{
    - contadorPozosAtravesados
    - resetearContadorPozos()
    - limitePozosExcedido(): boolean
    + avanzarComun(): Movimiento
    + avanzarPiquete(): Movimiento
    + avanzarControlPolicial(): Movimiento
    + avanzarPozo(): Movimiento
}

@enduml
@startuml(id=SINSUBCLASES)

       interface Vehiculo{
           + {abstract} avanzarComun(): Movimiento
           + {abstract} avanzarPiquete(): Movimiento
           + {abstract} avanzarControlPolicial(): Movimiento
           + {abstract} avanzarPozo(): Movimiento
       }

@enduml