@startuml
!include Evento.puml!SINSUBCLASES
!include EventoPosicion.puml
!include EventoVehiculo.puml
!include EventoPuntaje.puml

title Diagrama Clase completo de Evento


@enduml
@startuml(id=SINSUBCLASES)
!include EventoPuntaje.puml!SINSUBLCASES
!include EventoPosicion.puml!SINSUBLCASES
!include EventoVehiculo.puml!SINSUBLCASES

class Evento{
        + Evento( EventoPuntaje pun, EventoVehiculo veh, EventoPosicion pos)
        + setDireccionMovimiento( Direccion dir )
        + actualizarVehiculo( Vehiculo v ): Vehiculo
        + actualizarPuntaje( Movimiento m): Movimiento
        + actualizarPosicion( Celda p ): Celda
}
@enduml