@startuml
!include Obstaculo.puml!SINSUBCLASES

class Piquete{
    + avanzarEn( Vehiculo v ): Evento
}
class Pozo{
    + avanzarEn( Vehiculo v ): Evento
}
class ControlPolicial{
    - PROBABILIDAD_DE_SER_DEMORADO: float
    - generador: GeneradorAleatorio
    + ControlPolicial( GeneradorAleatorio generador): ControlPolicial
    + avanzarEn( Vehiculo v ): Evento
}

Piquete .up.|> Obstaculo
Pozo .up.|> Obstaculo
ControlPolicial .up.|> Obstaculo
@enduml

@startuml(id=SINSUBCLASES)
interface Obstaculo{
    + {abstract} avanzarEn( Vehiculo v ): Evento
}
@enduml