@startuml
!include Sorpresa.puml!SINSUBCLASES

class Favorable{
    + avanzarEn( Vehiculo v ): Evento
}
Favorable .up.|> Sorpresa
class Desfavorable{
    + avanzarEn( Vehiculo v ): Evento
}
Desfavorable .up.|> Sorpresa
class CambioVehiculo{
    + avanzarEn( Vehiculo v ): Evento
}
CambioVehiculo .up.|> Sorpresa
@enduml

@startuml(id=SINSUBCLASES)
interface Sorpresa{
    + {abstract} avanzarEn( Vehiculo v ): Evento
}
@enduml

