@startuml
!include Vehiculo.puml!SINSUBCLASES
Moto .down.|> Vehiculo
Auto .down.|> Vehiculo
cuatroPorCuatro .down.|> Vehiculo

class Moto{
    + avanzarComun(): Evento
    + avanzarPiquete(): Evento
    + avanzarControlPolicial(): Evento
    + avanzarPozo(): Evento
}
class Auto{
    + avanzarComun(): Evento
    + avanzarPiquete(): Evento
    + avanzarControlPolicial(): Evento
    + avanzarPozo(): Evento
}
class cuatroPorCuatro{
    - contadorPozosAtravesados: Integer
    - resetearContadorPozos()
    - limitePozosExcedido(): boolean
    + avanzarComun(): Evento
    + avanzarPiquete(): Evento
    + avanzarControlPolicial(): Evento
    + avanzarPozo(): Evento
}

@enduml
@startuml(id=SINSUBCLASES)

       interface Vehiculo{
           + {abstract} avanzarComun(): Evento
           + {abstract} avanzarPiquete(): Evento
           + {abstract} avanzarControlPolicial(): Evento
           + {abstract} avanzarPozo(): Evento
       }

@enduml