@startuml
title Diagrama Secuencia Auto Avanza Sin Obstaculos Y Sin Sorpresas
autonumber
actor Jugador

group "X unMovimiento"
activate Jugador

Jugador -> "posicion : Celda"++: avanzarHacia( ESTE, auto )

"posicion : Celda" -> "celdaEste : Celda"++: avanzarEn( auto )

"celdaEste : Celda" -> Comun++: avanzarEn( auto )
Comun -> "auto : Auto"++: avanzarComun()

create "unMovimiento : SinPenalizar"
"auto : Auto" -> "unMovimiento : SinPenalizar": SinPenalizar()
"auto : Auto" --> Comun: unMovimiento
deactivate "auto : Auto"

create "cambioVehiculo : SinCambiarVehiculo"
Comun -> "cambioVehiculo : SinCambiarVehiculo": SinCambiarVehiculo()

create "movimiento : Avanzar"
Comun -> "movimiento : Avanzar": Avanzar()

create "evento : Evento"
Comun -> "evento : Evento": Evento( unMovimiento, cambioVehiculo, movimiento)


Comun --> "celdaEste : Celda": evento
deactivate Comun
"celdaEste : Celda" --> "posicion : Celda": evento
deactivate "celdaEste : Celda"

"posicion : Celda" --> Jugador--: evento


Jugador -> "evento : Evento"++: actualizarPuntaje( puntaje )
Jugador <-- "evento : Evento"--: movimientoTotales

Jugador -> "evento : Evento"++: actualizarVehiculo( auto )
Jugador <-- "evento : Evento"--: auto

Jugador -> "evento : Evento"++: actualizarPosicion( posicion )
Jugador <-- "evento : Evento"--: celdaEste

end

@enduml