@startuml
title Diagrama Secuencia Auto Avanza Se Encuentra Con Piquete Y No Avanza

autonumber

actor Jugador

Jugador -> "posicion : Celda"++: avanzarHaciaLaDireccion( ESTE, auto )

activate Jugador
"posicion : Celda" -> "celdaEste : Celda"++: avanzarEn( auto )


"celdaEste : Celda" -> Piquete++: avanzarEn( auto )
Piquete -> "auto : Auto"++: avanzarPiquete()

create "ceroMovimiento : NoCambiarPuntaje"
"auto : Auto" -> "ceroMovimiento : NoCambiarPuntaje": SinCambiarPosicion()

create "cambioVehiculo : NoCambiarVehiculo"
"auto : Auto"  -> "cambioVehiculo : NoCambiarVehiculo": NoCambiarVehiculo()

create "movimiento : NoCambiarPosicion"
"auto : Auto"  -> "movimiento : NoCambiarPosicion": Avanzar()

create "evento : Evento"
"auto : Auto"  -> "evento : Evento": Evento( ceroMovimiento, cambioVehiculo, movimiento)

"auto : Auto" --> Piquete: evento
deactivate "auto : Auto"

Piquete --> "celdaEste : Celda": evento


"celdaEste : Celda" --> "posicion : Celda": evento
deactivate "celdaEste : Celda"

"posicion : Celda" --> Jugador--: evento


Jugador -> "evento : Evento"++: actualizarPuntaje( puntaje )
Jugador <-- "evento : Evento"--: movimientoTotales

Jugador -> "evento : Evento"++: actualizarVehiculo( auto )
Jugador <-- "evento : Evento"--: auto

Jugador -> "evento : Evento"++: actualizarPosicion( posicion )
Jugador <-- "evento : Evento"--: celdaEste

@enduml