@startuml
title Diagrama Secuencia Auto Avanza Sin Obstaculos Y Sin Sorpresas Vol. 2
autonumber
actor Jugador

group "X unMovimiento"
activate Jugador

Jugador -> "posicion : Posicion"++: avanzarHaciaLaDireccion( este, auto )

"posicion : Posicion" -> "posicion : Posicion"++: avanzarHaciaElEsteEn( auto )

"posicion : Posicion" -> "celdaEste : Celda"++: avanzarEn( auto )

"celdaEste : Celda" -> Comun++: avanzarEn( auto )
Comun -> "auto : Auto"++: avanzarComun()
create "unMovimiento : Movimiento"
"auto : Auto" -> "unMovimiento : Movimiento"
"auto : Auto" --> Comun: unMovimiento
deactivate "auto : Auto"
Comun --> "celdaEste : Celda": unMovimiento
deactivate Comun
"celdaEste : Celda" --> "posicion : Posicion": unMovimiento
deactivate "celdaEste : Celda"

note left
**Violación Tell Don't Ask**

Pregunta si es válido el
movimiento, ya que a veces no nos
podemos mover por un Piquete
end note


"unMovimiento : Movimiento" <- "posicion : Posicion"++: esPosible()
"unMovimiento : Movimiento" --> "posicion : Posicion": true
deactivate "unMovimiento : Movimiento"
"posicion : Posicion" -> "posicion : Posicion"++: setPosicion( celdaEste )

note left
**Violacion Don't Repeat Yourself**

Verificación para el seteo de la
posicion se repite a lo largo de
todos los diagramas, es decir,
es refactorizable.
end note


"posicion : Posicion" --> Jugador--: unMovimiento
deactivate "posicion : Posicion"
deactivate "posicion : Posicion"

Jugador -> "puntaje : Movimiento": sumarunMovimiento( unMovimiento )
end

@enduml