@startuml
title Diagrama Secuencia Cuatro por Cuatro Avanza Se Encuentra Con Pozo por Tercera Vez Y Se Penaliza

autonumber

actor Jugador

Jugador -> "posicion : Posicion"++: avanzarHaciaLaDireccion( este, cxc )

activate Jugador
"posicion : Posicion" -> "posicion : Posicion"++: avanzarHaciaElEsteEn( cxc )
"posicion : Posicion" -> "celdaEste : Celda"++: avanzarHaciaElEsteEn( cxc )

"celdaEste : Celda" -> Pozo++: avanzarEn( cxc )
Pozo -> "cxc : CuatroPorCuatro"++: avanzarPozo()
"cxc : CuatroPorCuatro" -> "cxc : CuatroPorCuatro"++: limiteDePozosExcedido()
"cxc : CuatroPorCuatro" --> "cxc : CuatroPorCuatro"--: true
create "dosMovimientos  : Movimiento"
"cxc : CuatroPorCuatro" -> "dosMovimientos  : Movimiento": Movimiento( 2 )
"cxc : CuatroPorCuatro" --> Pozo: dosMovimientos
deactivate "cxc : CuatroPorCuatro"
Pozo --> "celdaEste : Celda": dosMovimientos
deactivate Pozo
"celdaEste : Celda" --> "posicion : Posicion": dosMovimientos
deactivate "celdaEste : Celda"

note left
**Violación Tell Don't Ask**

Pregunta si es válido el
movimiento, ya que a veces no nos
podemos mover por un Piquete
end note

"dosMovimientos  : Movimiento" <- "posicion : Posicion"++: esPosible()
"dosMovimientos  : Movimiento" --> "posicion : Posicion": true
deactivate "dosMovimientos  : Movimiento"

"posicion : Posicion" -> "posicion : Posicion"++: setPosicion( celdaEste )

note left
**Violacion Don't Repeat Yourself**

Verificación para el seteo de la
posicion se repite a lo largo de
todos los diagramas, es decir,
es refactorizable.
end note

"posicion : Posicion" --> Jugador--: dosMovimientos
deactivate "posicion : Posicion"
deactivate "posicion : Posicion"
Jugador -> "puntaje: Movimiento"++: sumarMovimientos( dosMovimientos )

deactivate Jugador
@enduml