@startuml
title Un Auto Avanza Y Es Detenido Por Un Control Policial

autonumber

Jugador -> "posicion : Celda"++: avanzarHaciaLaDireccion(ESTE)

activate Jugador
"posicion : Celda" -> "celdaEste : Celda"++: avanzarEn( auto )


"celdaEste : Celda" -> " : ControlPolicial"++: avanzarEn( auto )

" : ControlPolicial" -> "auto : Vehiculo": avanzarControlPolicial()

create "penalizacion : Penalizacion"
"auto : Vehiculo"-> "penalizacion : Penalizacion": Penalizacion(3)

create "cambioVehiculo : NoCambiarVehiculo"
"auto : Vehiculo"-> "cambioVehiculo : NoCambiarVehiculo": NoCambiarVehiculo()

create "avanzar : Avanzar"
"auto : Vehiculo"-> "avanzar : Avanzar": Avanzar()

create "evento : Evento"
"auto : Vehiculo" -> "evento : Evento": Evento(penalizacion), cambioVehiculo, avanzar)

"auto : Vehiculo" --> " : ControlPolicial": evento
" : ControlPolicial" --> "celdaEste : Celda": evento
"celdaEste : Celda" --> "posicion : Celda": evento
"posicion : Celda" -> "evento : Evento"++: setDireccion( ESTE )
"posicion : Celda" --> Jugador : evento

@enduml