@startuml
title Diagrama Secuencia Moto Atraviesa La Ciudad Y Encuentra Sorpresa Cambio Vehiculo con Auto

autonumber

actor Jugador

Jugador -> "posicion : Celda"++: getCelda(ESTE )

activate Jugador
"posicion : Celda" --> Jugador: celdaEste
deactivate "posicion : Celda"
Jugador -> "celdaEste : Celda"++: avanzarEn( moto )


"celdaEste : Celda" -> "sorpresa : CambioVehiculo"++: avanzarEn( moto )

create "eventoPuntaje : SinPenalizar"
"sorpresa : CambioVehiculo"-> "eventoPuntaje : SinPenalizar": SinPenalizar()

create "eventoVehiculo : SiguienteVehiculo"
"sorpresa : CambioVehiculo" -> "eventoVehiculo : SiguienteVehiculo": SiguienteVehiculo()

create "eventoPosicion : Avanzar"
"sorpresa : CambioVehiculo"  -> "eventoPosicion : Avanzar": Avanzar()

create "evento : Evento"
"sorpresa : CambioVehiculo"  -> "evento : Evento": Evento( eventoPuntaje, eventoVehiculo, eventoPosicion)

"sorpresa : CambioVehiculo" --> "celdaEste : Celda": evento
"celdaEste : Celda" -> "sorpresa : CambioVehiculo": siguiente()
"sorpresa : CambioVehiculo" --> "celdaEste : Celda"--: estado
deactivate "celdaEste : Celda"

Jugador -> "evento : Evento"++: setDireccion( ESTE )
deactivate "evento : Evento"

deactivate Jugador


Jugador -> "evento : Evento"++: actualizarPuntaje( puntaje )
activate Jugador
Jugador <-- "evento : Evento"--: movimientoTotales
deactivate Jugador

Jugador -> "evento : Evento"++: actualizarVehiculo( moto )
activate Jugador
"evento : Evento" -> "moto : Moto"++: siguiente()
"moto : Moto" --> "evento : Evento"--: auto
Jugador <-- "evento : Evento"--: auto
deactivate Jugador


Jugador -> "evento : Evento"++: actualizarPosicion( posicion )
activate Jugador
Jugador <-- "evento : Evento"--: celdaEste
deactivate Jugador

@enduml