@startuml
title Diagrama Secuencia Vehiculo Atraviesa La Ciudad Y Encuentra Sorpresa Desfavorable

autonumber

actor Jugador

Jugador -> "posicion : Celda"++: avanzarHaciaLaDireccion( ESTE, v )

activate Jugador
"posicion : Celda" -> "celdaEste : Celda"++: avanzarEn( v )


"celdaEste : Celda" -> "sorpresa : CambioVehiculo"++: avanzarEn( v )

create "movimientos : AumentoPorcentaje"
"sorpresa : CambioVehiculo"-> "movimientos : AumentoPorcentaje": AumentoPorcentaje( 25 )

create "cambioVehiculo : NoCambiarVehiculo"
"sorpresa : CambioVehiculo" -> "cambioVehiculo : NoCambiarVehiculo": NoCambiarVehiculo()

create "movimiento : Avanzar"
"sorpresa : CambioVehiculo"  -> "movimiento : Avanzar": Avanzar()

create "evento : Evento"
"sorpresa : CambioVehiculo"  -> "evento : Evento": Evento( movimientos, cambioVehiculo, movimiento)

"sorpresa : CambioVehiculo" --> "celdaEste : Celda"--: evento

"celdaEste : Celda" --> "posicion : Celda": evento
deactivate "celdaEste : Celda"
"posicion : Celda" -> "evento : Evento": setDireccion( ESTE )
"posicion : Celda" --> Jugador--: evento


Jugador -> "evento : Evento"++: actualizarPuntaje( puntaje )
"evento : Evento" -> "puntaje : Movimiento": aplicarAumento( 25 )
"puntaje : Movimiento" --> "evento : Evento": movimientoTotales
Jugador <-- "evento : Evento"--: movimientoTotales

Jugador -> "evento : Evento"++: actualizarVehiculo( auto )
Jugador <-- "evento : Evento"--: auto

Jugador -> "evento : Evento"++: actualizarPosicion( posicion )
Jugador <-- "evento : Evento"--: celdaEste

@enduml