@startuml
title Diagrama Secuencia Auto Avanza Se Encuentra Con Piquete Y No Avanza

autonumber

actor Jugador

Jugador -> "posicion : Celda"++: avanzarHaciaLaDireccion( ESTE, auto )

activate Jugador
"posicion : Celda" -> "celdaEste : Celda"++: avanzarEn( auto )


"celdaEste : Celda" -> Piquete++: avanzarEn( auto )
Piquete -> "auto : Auto"++: avanzarPiquete()

create "eventoPuntaje : NoCambiarPuntaje"
"auto : Auto" -> "eventoPuntaje : NoCambiarPuntaje": NoCambiarPuntajes()

create "eventoVehiculo : NoCambiarVehiculo"
"auto : Auto"  -> "eventoVehiculo : NoCambiarVehiculo": NoCambiarVehiculo()

create "eventoPosicion : NoCambiarPosicion"
"auto : Auto"  -> "eventoPosicion : NoCambiarPosicion": NoCambiarPosicion()

create "evento : Evento"
"auto : Auto"  -> "evento : Evento": Evento( eventoPuntaje, eventoVehiculo, eventoPosicion)

"auto : Auto" --> Piquete: evento
deactivate "auto : Auto"

Piquete --> "celdaEste : Celda": evento

deactivate Piquete
"celdaEste : Celda" --> "posicion : Celda": evento
deactivate "celdaEste : Celda"



"posicion : Celda" -> "evento : Evento"++: setDireccion( ESTE )
deactivate "evento : Evento"
"posicion : Celda" --> Jugador--: evento
deactivate Jugador


Jugador -> "evento : Evento"++: actualizarPuntaje( puntaje )
activate Jugador
Jugador <-- "evento : Evento"--: movimientoTotales
deactivate Jugador

Jugador -> "evento : Evento"++: actualizarVehiculo( auto )
activate Jugador
Jugador <-- "evento : Evento"--: auto
deactivate Jugador

Jugador -> "evento : Evento"++: actualizarPosicion( posicion )
activate Jugador
Jugador <-- "evento : Evento"--: celdaEste
deactivate Jugador
@enduml