@startuml
title Diagrama Secuencia Moto Avanza Se Encuentra Con Pozo  Y Se Penaliza 3 movimientos

autonumber

actor Jugador

Jugador -> "posicion : Celda"++: getCelda(ESTE )
activate Jugador
"posicion : Celda" --> Jugador: celdaEste
deactivate "posicion : Celda"

Jugador -> "celdaEste : Celda"++: avanzarEn(moto)
"celdaEste : Celda" -> " : Pozo"++: avanzarEn( moto )
" : Pozo" -> "moto : Moto"++: avanzarPozo()

create "eventoPuntaje :Penalizacion"
"moto : Moto"-> "eventoPuntaje :Penalizacion": Penalizacion(3)

create "eventoVehiculo : NoCambiarVehiculo"
"moto : Moto"-> "eventoVehiculo : NoCambiarVehiculo": NoCambiarVehiculo()

create "eventoPosicion : Avanzar"
"moto : Moto"-> "eventoPosicion : Avanzar": Avanzar()

create "evento : Evento"
"moto : Moto"  -> "evento : Evento": Evento( eventoPuntaje, eventoVehiculo, eventoPosicion)


"moto : Moto" --> " : Pozo": evento
deactivate "moto : Moto"

" : Pozo" --> "celdaEste : Celda": evento
"celdaEste : Celda" -> " : Pozo": siguiente()
" : Pozo" --> "celdaEste : Celda": estado
deactivate " : Pozo"


"celdaEste : Celda" --> Jugador: evento
deactivate "celdaEste : Celda"

Jugador -> "evento : Evento"++: setDireccion( ESTE )
deactivate "evento : Evento"

deactivate Jugador

Jugador -> "evento : Evento"++: actualizarPuntaje( puntaje )
activate Jugador
Jugador <-- "evento : Evento"--: movimientoTotales
deactivate Jugador

Jugador -> "evento : Evento"++: actualizarVehiculo( moto )
activate Jugador
Jugador <-- "evento : Evento"--: moto
deactivate Jugador

Jugador -> "evento : Evento"++: actualizarPosicion( posicion )
activate Jugador
Jugador <-- "evento : Evento"--: celdaEste
deactivate Jugador

@enduml