@startuml
title Diagrama Secuencia Auto Avanza Se Encuentra Con Piquete Y No Avanza

autonumber

actor Jugador

Jugador -> "posicion : Celda"++: avanzarHaciaLaDireccion( ESTE, auto )

activate Jugador
"posicion : Celda" -> "celdaEste : Celda"++: avanzarEn( auto )


"celdaEste : Celda" -> Piquete++: avanzarEn( auto )
Piquete -> "auto : Auto"++: avanzarPiquete()

create "eventoPuntaje : NoCambiarPuntaje"
"auto : Auto" -> "eventoPuntaje : NoCambiarPuntaje": NoCambiarPuntaje()

create "eventoVehiculo : NoCambiarVehiculo"
"auto : Auto"  -> "eventoVehiculo : NoCambiarVehiculo": NoCambiarVehiculo()

create "eventoPosicion : NoCambiarPosicion"
"auto : Auto"  -> "eventoPosicion : NoCambiarPosicion": NoCambiarPosicion()

create "evento : Evento"
"auto : Auto"  -> "evento : Evento": Evento( eventoPuntaje, eventoVehiculo, eventoPosicion)

"auto : Auto" --> Piquete: evento
deactivate "auto : Auto"

Piquete --> "celdaEste : Celda": evento


"celdaEste : Celda" --> "posicion : Celda": evento
deactivate "celdaEste : Celda"

"posicion : Celda" -> "evento : Evento"++: setDireccion( ESTE )
deactivate "evento : Evento"
"posicion : Celda" --> Jugador--: evento


Jugador -> "evento : Evento"++: actualizarPuntaje( puntaje )
Jugador <-- "evento : Evento"--: movimientoTotales

Jugador -> "evento : Evento"++: actualizarVehiculo( auto )
Jugador <-- "evento : Evento"--: auto

Jugador -> "evento : Evento"++: actualizarPosicion( posicion )
Jugador <-- "evento : Evento"--: posicion

@enduml